### ISSUE TITLE
github: comply with Go license terms

### ISSUE THREAD

**Issue by mappu** [ory-am/fosite#123]
See https://github.com/ory-am/hydra/issues/300 for context.

**Comment by arekkas** [comment]
resolved

**Comment by mappu** [comment]
Not resolved, I think `The security first OAuth2 & OpenID Connect framework for Google's Go Language. ` in README.md is still violating.

But violation is based on your interpretation of the license. I have no skin in this game, can't force you if you interpret it differently to me.

**Comment by arekkas** [comment]
whoops thanks, fixed!
